# Generated by Django 4.1.3 on 2022-12-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('not disclosed', 'not disclosed')], default='male', max_length=20)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('work_at', models.CharField(blank=True, max_length=50, null=True)),
                ('lives_in', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
