# Generated by Django 4.1.3 on 2022-12-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_blockusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockusers',
            name='blockedusers',
            field=models.ManyToManyField(blank=True, null=True, related_name='bloked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
