# Generated by Django 4.1.3 on 2022-12-27 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_blockusers_blockedusers_alter_blockusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockusers',
            name='blockedusers',
            field=models.ManyToManyField(blank=True, related_name='bloked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
