# Generated by Django 4.1.3 on 2023-01-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_blockusers_blockedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='followlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_list', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL)),
                ('pending_req', models.ManyToManyField(blank=True, related_name='pending_req', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
